CHANGES.rst
src/ZEO/ClientStorage.py
src/ZEO/cache.py
src/ZEO/tests/test_cache.py
src/ZEO/zrpc/connection.py

Changed loadBefore to operate more like load behaved, especially
with regard to the load lock.  This allows ZEO to work with the
upcoming ZODB 5, which used loadBefore rather than load.
Reimplemented load using loadBefore, this testing loadBefore
extensively via existing tests.

Load uses load before

---

src/ZEO/ClientStorage.py
src/ZEO/StorageServer.py
src/ZEO/asyncio/server.py
src/ZEO/asyncio/tests.py
src/ZEO/cache.py
src/ZEO/interfaces.py
src/ZEO/tests/forker.py
src/ZEO/tests/protocols.test
src/ZEO/tests/testZEO2.py

ZEO's vote error handling was extremely and weirdly complicated.
There's a hysterical explanation: Originally, the ZEO protocol was
synchronous and mirrored the storage API. That was too slow, so store
was made asynchronous.  But then there was no way to return new
serials or errors, so we added a serialnos client API that the server called
during TPC. This was used both to send serials and errors to the client.  Later, tpc_vote
was added, which is a synchronous method. That would have been an
excellent opportunity to fix this, but noooooooooo.
I'd like the server vote logic to get simpler, and we also want to get rid
of serialnos, as it makes it hard to commit multiple transactions at
once on the client.  We can't get rid of serialnos now, because the
client needs to work with old …

Simplify server vote error handling

---

doc/zeo-client-cache-tracing.txt

I haven't actually compared the output snippets (yet), but at least the script references are right now.
Here we're referring to full module paths. The alternative would be to add these scripts to the `entry-points` setup argument as zeostats and zeosimul.

Update zeo-client-cache-tracing to use accurate script names.

---

CHANGES.rst
src/ZEO/cache.py

This code path was using a constant `""` for the `tid`, which is a `str` on Py3, not bytes, leading to:
```python
Traceback (most recent call last):
...
File "//zodbshootout-main/src/zodbshootout/_runner.py", line 148, in make_factory
_db = db_conf.open()
File "//site-packages/ZODB/config.py", line 130, in open
**options)
File "///site-packages/ZODB/DB.py", line 443, in __init__
temp_storage.load(z64, '')
File "//ZEO/src/ZEO/ClientStorage.py", line 825, in load
result = self.loadBefore(oid, m64)
File "//ZEO/src/ZEO/ClientStorage.py", line 834, in loadBefore
result = self._cache.loadBefore(oid, tid)
File "//ZEO/src/ZEO/cache.py", line 139, in _locked_wrapper
return func(inst, *args, **kwargs)
File "//ZEO/src/ZEO/cache.py", line 560, in loadBefore
self._trace(0x24, oid, "", before_tid)
File …
```

Fix tracing of loadBefore with empty tids on Py3.

---

CHANGES.rst
src/ZEO/ClientStorage.py
src/ZEO/asyncio/client.py
src/ZEO/tests/test_client_credentials.py

This is experimental in that passing credentials will cause
connections to an ordinary ZEO server to fail, but it facilitates
experimentation with custom ZEO servers. Doing this with custom ZEO
clients would have been awkward due to the many levels of
composition involved.
In the future, we expect to support server security plugins that
consume credentials for authentication (typically over SSL).
Note that credentials are opaque to ZEO. They can be any object with
a true value.  The client mearly passes them to the server, which
will someday pass them to a plugin.

Added the ability to pass credentials when creating client storages.

---

.travis.yml
CHANGES.rst
src/ZEO/Exceptions.py
src/ZEO/tests/testZEO.py

When applications retry jobs that raise transient errors, jobs (e.g. web
requests) with disconnect errors will be retried. Together with
blocking synchronous ZEO server calls for a limited time while
disconnected, this change should allow brief disconnections due to
server restart to avoid generating client-visible errors (e.g. 500
web responses).
Fixes #56

Client disconnect errors are now transient errors.

---

CHANGES.rst
src/ZEO/StorageServer.py
src/ZEO/tests/testZEO.py

Allowing the client to avoid an extra round trip during
cache verification.

- The ZEO server register method now returns the storage last transaction

---

CHANGES.rst
README.rst
src/ZEO/ClientStorage.py
src/ZEO/StorageServer.py
src/ZEO/component.xml
src/ZEO/tests/ConnectionTests.py
src/ZEO/tests/testConfig.py
src/ZEO/tests/test_sync.py
src/ZEO/zconfig.py

Added a ClientStorage server-sync configuration option and
server_sync constructor argument to force a server round trip at
the beginning of transactions to wait for any outstanding
invalidations at the start of the transaction to be delivered.

Server sync

---

CHANGES.rst
src/ZEO/tests/ConnectionTests.py
src/ZEO/tests/forker.py
src/ZEO/tests/testZEO.py

You must pass a log option specifying a log file name.

When creating an ad hoc server, a log file isn't created by default

---

src/ZEO/asyncio/server.py
src/ZEO/nagios.rst
src/ZEO/tests/drop_cache_rather_than_verify.txt
src/ZEO/tests/new_addr.test
src/ZEO/tests/testConfig.py
src/ZEO/tests/testZEO.py
src/ZEO/tests/testZEO2.py
src/ZEO/tests/test_client_credentials.py
src/ZEO/tests/test_client_side_conflict_resolution.py
src/ZEO/tests/testssl.py
src/ZEO/tests/threaded.py

To accomplish this, it was necessary to rearrange the tests so that
tests that ran servers in threads rather than using multiprocessing
into their own layer.  This is due to a bug currently in uvloop that
prevents using running uvloop servers in a process and in subprocesses
created with multiprocessing:
https://github.com/MagicStack/uvloop/issues/39
To run the tests with uvloop installed, it's necessary to use the
``-j`` option to run layers in separate processes.

Use uvloop in the single-threaded server

---

CHANGES.rst
setup.py

Exit with failure codes instead of success codes on unsupported Python versions.

---

CHANGES.rst
src/ZEO/asyncio/client.py
src/ZEO/asyncio/tests.py
src/ZEO/tests/drop_cache_rather_than_verify.txt
src/ZEO/tests/testZEO.py

On Python 2, waiting on a future result with a timeout is very
expensive. (Because conditions with timeouts are very expensive.)
The thing is, we still want to use timeouts when we're disconnected.
We don't want requests to fail right away of the disconnection is
short.
We do a bit of a dance to only use a timeout if we're disconnected.

Avoid waiting on futures using timeouts -> major performance win on Python 2

---

CHANGES.rst
src/ZEO/runzeo.py
src/ZEO/tests/testZEOServer.py

When `StorageServer.__init__` fails with an exception, the error is masked by a subsequent AttributeError: 'ZEOServer' object has no attribute 'server'.
I propose to add a close_server function to ZEOServer, which can handle the case of non-existing server. This is also for the benefit of subclasses, which get better access to the server lifecycle.

AttributeError 'server' when StorageServer creation fails

---

CHANGES.rst
MANIFEST.in
setup.cfg
setup.py

(I don't actually expect this to work until #91 is merged because of the SSL test problems.)
Fixes #93.
Fixes #92 
Example:
```
$ pip install .
Processing /.../ZEO
ZEO requires Python '>=2.7.9,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*' but the running Python is 3.3.6`
```

Use python_requires and extras_require for version-specific deps

---

buildout.cfg
setup.py
src/ZEO/asyncio/marshal.py
src/ZEO/tests/test_marshal.py
tox.ini

On python 2, calling undoLog via ZEO with ZopeUndo.Prefix filter, ZEO server raise an exception:
```
File ".../src/ZEO/asyncio/marshal.py", line 114, in pickle_server_decode
return unpickler.load() # msgid, flags, name, args
File ".../src/ZEO/asyncio/marshal.py", line 164, in server_find_global
raise ImportError("import error %s: %s" % (module, msg))
ImportError: import error copy_reg:
```
The problem was introduced when ZopeUndo.Prefix was changed and subclassed from the object.
This PR tries to fix the problem.

fix ZopeUndo.Prefix decode on python 2

---

src/ZEO/asyncio/server.py

Closes #107.
@jimfulton I couldn't figure the testing story out well enough to write a simple test for this case, but returning early after closing the server protocol seems right by inspection.

Return early after decode error.

---

.travis.yml
CHANGES.rst
src/ZEO/asyncio/client.py
src/ZEO/asyncio/marshal.py
src/ZEO/asyncio/mtacceptor.py
src/ZEO/asyncio/server.py
src/ZEO/asyncio/tests.py
src/ZEO/tests/ConnectionTests.py
src/ZEO/tests/IterationTests.py
src/ZEO/tests/ThreadTests.py
src/ZEO/tests/testConversionSupport.py
src/ZEO/tests/testTransactionBuffer.py
src/ZEO/tests/testZEO.py
src/ZEO/tests/testZEO2.py
src/ZEO/tests/test_cache.py
src/ZEO/tests/testssl.py

Fixes #107 
I also spent time trying to understand why so many of the tests are failing. I don't have answers for all of it, but I think this puts us in a better state.
- Python 2 (both CPython and PyPy) is *incredibly slow*. The `FileStorageTests`, `FileStorageSSLTests` and `BlobAdaptedFileStorageTests` can take 8 to 15 minutes each. And we run them multiple times. Since Travis kills a test if there is no output in 10 minutes, Python 2 was just getting forcibly shutdown. Remedy: increase verbosity so we get some output. Now, they still fail due to some threads being left behind, but at least they're not terminated. And we can see that the 'Connection' errors that were prevelant in the logs for #107 aren't there anymore. I'm not sure why they're so slow---the Python 2 tests with msgpack …

Add zodbpickle to server_find_global.

---

CHANGES.rst
src/ZEO/ClientStorage.py
src/ZEO/_compat.py
src/ZEO/tests/forker.py
src/ZEO/tests/testZEO.py

No specific test case, though.

Disallow using strings as addresses on Windows. Fixes #106.

---

.travis.yml
CHANGES.rst
setup.py
src/ZEO/ClientStorage.py
src/ZEO/StorageServer.py
src/ZEO/asyncio/client.py
src/ZEO/asyncio/marshal.py
src/ZEO/asyncio/server.py
src/ZEO/asyncio/testing.py
src/ZEO/asyncio/tests.py
src/ZEO/tests/ConnectionTests.py
src/ZEO/tests/ZEO4/zrpc/connection.py
src/ZEO/tests/ZEO4/zrpc/marshal.py
src/ZEO/tests/testConversionSupport.py
src/ZEO/tests/testTransactionBuffer.py
src/ZEO/tests/testZEO.py
src/ZEO/tests/testZEO2.py
src/ZEO/tests/utils.py

Fixes #104.
I don't think any of those attributes were part of ZEO's public API.

Rename all 'async' to 'async_' for compatibility with Python 3.7.

---

CHANGES.rst
src/ZEO/_compat.py
src/ZEO/asyncio/marshal.py
src/ZEO/tests/ZEO4/zrpc/marshal.py
src/ZEO/tests/testZEO.py

I also snuck the fix for ZEO_MTACCEPTOR tests in (use IPv4 instead of v6), so we have green builds (🙌 ).
On Python 2, this will necessitate that the client and server are both running at least this version of ZEO (because before this, ZEO wasn't using zodbpickle to read the wire so they won't be able to decode the protocol). Or use msgpack.

Use pickle protocol 3 on the wire.

---

CHANGES.rst
setup.py

https://github.com/msgpack/msgpack-python/#very-important-notes-for-existing-users

'msgpack-python' egg was renamed 'msgpack'

---

src/ZEO/tests/test_client_side_conflict_resolution.py
tox.ini

Otherwise when you run `tox` this test will create a `data.fs` using Python 2 and then the same test will fail on Python 3 because there already is a `data.fs` in the current working directory, but it has an incompatible format.
See https://github.com/zopefoundation/ZEO/issues/140#issuecomment-486650942

Use a temporary directory in tests

---

README.rst
src/ZEO/runzeo.py
src/ZEO/tests/ZEO4/runzeo.py

So using `--help` option will show `--configure` option:
```
$ ./venv/bin/runzeo --help
Start the ZEO storage server.
Usage: ./venv/bin/runzeo [-C URL] [-a ADDRESS] [-f FILENAME] [-h]
Options:
-C/--configure URL -- configuration file or URL
[...]
```
`--configuration` don't work and `--configure` option seems to be more standard between Z-tools.
closes: #138
#138 provides more explanation about it.

Use of --configure option instead of --configuration

---

README.rst

The variable is named `address` and is called `addr` in the following lines. This PR uses `address` consistently.

Fix variable name in code example

---

src/ZEO/StorageServer.py
src/ZEO/tests/ConnectionTests.py
src/ZEO/tests/TestThread.py
src/ZEO/tests/ThreadTests.py
src/ZEO/tests/ZEO4/StorageServer.py
src/ZEO/tests/ZEO4/zrpc/client.py
src/ZEO/tests/testConnection.py
src/ZEO/tests/zeo_blob_cache.test

This PR replaces `Thread.isAlive()` calls by `Thread.is_alive()` calls because the first method is deprecated. 
Currently, several `PendingDeprecationWarning` are raised when `tox` runs:
`
Set up .ZEO Connection DocTests in 0.003 seconds.
Running:
1/1 (100.0%)/home/stephane/src/ZEO/.tox/py37/lib/python3.7/site-packages/ZEO/tests/testConnection.py:1: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
`

Replace deprecated occurences of Thread.isAlive() by Thread.is_alive()

---

doc/server.rst

This PR updates a link to zdaemon package in the documentation.

Update package link from pypi.python.org to pypi.org

---

src/ZEO/StorageServer.py
src/ZEO/tests/testZEO.py

Starting from 1999 (b3805a2f "just getting started") only modified - not
just created - objects were included into ZEO invalidation messages:
https://github.com/zopefoundation/ZEO/commit/b3805a2f#diff-52fb76aaf08a1643cdb8fdaf69e37802R126-R127
In 2000 this behaviour was further changed to not send invalidation
message at all if the only objects a transaction has were the created ones:
https://github.com/zopefoundation/ZEO/commit/230ffbe8#diff-52fb76aaf08a1643cdb8fdaf69e37802L163-R163
In 2016 the latter was reconsidered as bug and fixed in ZEO5 because
ZODB5 relies more heavily on MVCC semantic and needs to be notified
about every transaction committed to storage to be able to properly
update ZODB.Connection view:
https://github.com/zopefoundation/ZEO/commit/02943acd#diff-52fb76aaf08a1643cdb …

Include both modified and just created objects into invalidations

---

CHANGES.rst
src/ZEO/asyncio/client.py

Currently loadBefore and prefetch spawn async protocol.load_before task,
and, after waking up on its completion, populate the cache with received
data. But in between the time when protocol.load_before handler is run
and the time when protocol.load_before caller wakes up, there is a
window in which event loop might be running some other code, including
the code that handles invalidateTransaction messages from the server.
This means that cache updates and cache invalidations can be processed on
the client not in the order that server sent it. And such difference in
the order can lead to data corruption if e.g server sent
<- loadBefore oid serial=tid1 next_serial=None
<- invalidateTransaction tid2 oid
and client processed it as
invalidateTransaction tid2 oid
cache.store(oid, tid1, …

client: Fix cache corruption on loadBefore and prefetch

---

doc/clients.rst

I suspect the other underscore containing settings have the same typo - but I hadn't have time to check it, so I'm leaving it as a suggestion for further work. Sorry 'bout that.

Fix typo client_label -> client-label for strings configuration files

---

doc/clients.rst

`cache-size-bytes` is not a valid option

Replaced 'cache-size-bytes' with 'cache-size' in the documentation

---

src/ZEO/tests/drop_cache_rather_than_verify.txt

This PR adds more debugging code in the hope to understand the race condition in the `drop_cache_rather_than_verity` test. In my local environment, the race does not occur. Thus, the need to use the github tests (where the race sometimes occurs).

hunt for the drop cache race condition

---

CHANGES.rst
src/ZEO/tests/testZEO.py

Fixes #198.
The ZEO tests have the task to verify proper ZEO functioning, not to test storages. If ZEO works correctly and a storage works correctly, then ZEO should work correctly with this storage.
This PR drops the ZEO tests with the storages `DemoStorage`, `FileStorage` without blobs, `HexFileStorage` and `ClientHexFileStorage`. It retains the tests with `Filestorage` with shared or server side blobs and `MappingStorage`.
The `MappingStorage` tests cover the case "storage without blobs". It is used instead of `FileStorage` without blobs to increase the chance to detect race conditions (`MappingStorage` has slightly different latency from `FileStorage` because the data is stored in RAM rather than on disk).

Reduce ZEO testing time by dropping tests with some storages

---

setup.py
src/ZEO/tests/test_cache.py

We can use stdlib random module and manually adjust randint to behave
exactly as before Python3, so that testdata are matched exactly as before.
Also drop unnecessary `random.seed(42)` in cache_run. It is not needed
there because random is not used in cache_run at all.
Based on work of @d-maurer in https://github.com/zopefoundation/ZEO/pull/195 .

tests: Drop use of random2

---

src/ZEO/tests/ConnectionTests.py

--------
kirr:
Always use appropriate logger object set up in a module. It was only
ZEO/tests/ConnectionTests.py which was using logging directly even
though corresponding logger object was set up in that module.
Extracted from https://github.com/zopefoundation/ZEO/pull/195

*: Do not use logging directly to emit log messages

---

.meta.toml
tox.ini

Since https://github.com/zopefoundation/ZODB/commit/a94d63c552d6 (part
of https://github.com/zopefoundation/ZODB/pull/368) some ZODB tests are
marked as being long to help skipping them easily during development via
running tests only at level 1.
But by default we want to continue to run all tests.
-> Adjust tox to run tests at all levels explicitly, since
zope-testrunner's default is to run tests at level 1 only.

Run tests at all levels

---

src/ZEO/scripts/zeopack.py
src/ZEO/scripts/zeopack.test

closes: #214
This PR changes the `zeopack` exit value to 1 when all connections to server are a failure. Currently, `zeopack` outputs `Couldn't connect to: xxx` and exits with 0. I think it should be an error exit value than a succes. 
The usecase is described in #214. This PR implements  the solution **a** (as defined in issue #214) because the [`usage`](https://github.com/zopefoundation/ZEO/blob/83730901e5d7bcb0916d5391f5907e5f9d3a32e7/src/ZEO/scripts/zeopack.py#L12) constant documents `zeopack` as `Pack one or more storages hosted by ZEO servers`.

exit value is 1 if all connection to servers fail

---

.github/workflows/tests.yml
.gitignore
.meta.toml
CHANGES.rst
setup.cfg
setup.py
tox.ini

I had to disable flake8 checks, so isort-ing the imports is not enforced.

Fix GHA + support Python 3.11.

---

CHANGES.rst
src/ZEO/asyncio/client.py
src/ZEO/asyncio/connectco_2.py
src/ZEO/asyncio/connectco_3.py
src/ZEO/asyncio/tests.py

Fixes #226.
This PR is an alternative to #227. Both fix #226.
While #227 fixes the immediate cause for the #226 failure, i.e. the connection process had made the implicit assumption that the loop was already running not fulfilled with ZEO, this PR approaches the problem in a more general way: the connection process is not implemented by ZEO but by foreign code; this code may expect a standard `Task`/coroutine executor, not the optimized but limited one of the ZEO implementation. For this reason, this PR uses a standard `asyncio.Task` to control the connection process.
A standard `Task` automatically ensures that its first step is only run when the loop is running.

Fix #226 using a standard `asyncio.Task` 

---

.meta.toml
setup.cfg
src/ZEO/StorageServer.py
src/ZEO/TransactionBuffer.py
src/ZEO/_compat.py
src/ZEO/asyncio/futures.py
src/ZEO/asyncio/marshal.py
src/ZEO/runzeo.py
src/ZEO/scripts/cache_stats.py
src/ZEO/scripts/zeoqueue.py
src/ZEO/server.xml
src/ZEO/tests/IterationTests.py
src/ZEO/tests/testZEO2.py
src/ZEO/tests/testZEOOptions.py
src/ZEO/tests/testZEOServer.py

Remove Python 2 leftovers.
